### ISSUE TITLE
Lorem Ipsum on confirmation modal

### ISSUE THREAD

**Issue by steveparks** [tv2regionerne/statamic-passport#5]
When creating a Personal Access Token, the confirmation modal displays a paragraph of Lorem Ipsum below the header, above the token.

Screenshot
![CleanShot 2024-05-22 at 18 14 29@2x](https://github.com/tv2regionerne/statamic-passport/assets/95851/07874a5e-4574-45fb-871c-ece61db6a36f)

**Comment by SylvesterDamgaard** [comment]
You are right. That shouldn't be there. 
https://github.com/tv2regionerne/statamic-passport/blob/b4988ff14aba6c6378a7608d3897defd7a543897/resources/js/components/tokens/View.vue#L9

**Comment by steveparks** [comment]
I've started a pull request in case that's helpful: https://github.com/tv2regionerne/statamic-passport/pull/6

(but am rusty with Github and have forgotten how to auto link it to this issue)

**Comment by sylvesterdamgaard** [comment]
Merged 😊
